# Specifies the Docker Compose file format version.
version: '3.8'

# Defines the services that make up your application. 
services:
  app: # Name of the service.
    build: # Instructions to build the Docker image.
      context: .  # The build context location
      dockerfile: Dockerfile # The name of the Dockerfile.
    image: my_streamlit_app:v1.0 # Names the image to be built with a tag.
    ports: 
      - "8501:8501" # Maps port 8501 on the host to port 8501 in the container.
    volumes:
      - .:/app # Mounts the current directory on the host to '/app' inside the container, allowing for live code changes.
    environment:
    # Sets the environment variable PYTHONUNBUFFERED to '1' to ensure Python output is directly dumped to the terminal.
      - PYTHONUNBUFFERED=1 
    # Overrides the default command to start the Streamlit application with specific flags:
    # --server.port=8501 specifies the port Streamlit should run on.
    # --server.headless=true enables headless mode for running in containers.
    # --server.address=0.0.0.0 makes Streamlit listen on all network interfaces.
    command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.headless=true", "--server.address=0.0.0.0"]
